#!/bin/bash

# pings all network devices in the local network and sends out emails if some 
# are not responding

# best done with a daily cronjob like 0 7 * * * /home/marsPortal/misc/monitor_network_devices.sh

BASEDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

source $BASEDIR/config.txt

LOG=/tmp/monitor_network_devices.log
HISTORYLOG=/$BASEDIR/monitor_network_devices_history.log

TIMESTAMP=`date +%Y%m%d-%H%M%S`

rm $LOG
rm $LOG.tmp

while read line           
do
    l=`echo $line | tr -d ' \t\n\r\f'`
    if [[ ! $l =~ \# ]]; then
        if [ ! -z "$l" ]; then
  	  /bin/sleep 1
  	  /bin/ping -c 10 $l  >> $LOG.tmp
	  if [ $? -eq 0 ]; then
  	    echo  
  	    #echo "$l" reachable >> $LOG
            echo "$TIMESTAMP;$l;online" >> $HISTORYLOG
  	  else
  	    echo "$l" not reachable >> $LOG
            echo "$TIMESTAMP;$l;offline" >> $HISTORYLOG
  	  fi
       fi
    fi
done < $BASEDIR/monitor_network_devices.txt          

if [ -e $LOG ]; then
  echo "" >> $LOG
  echo `date` >> $LOG
  echo "" >> $LOG
  echo "(mail generated by script marsPortal:///home/marsPortal/misc/monitor_network_devices.sh)" >> $LOG
  SUBJECT="`echo "mars-admin Internal network devices check: "` `date +%Y%m%d-%H%M`"
  $BASEDIR/send-mail.sh "$SUBJECT" "`cat $LOG`"
fi

